apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  selector:
    component: jupyter
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30000
  type: NodePort